[book]
authors = ["The Open Source Way Contributors"]
language = "zh-cn"
src = "."
title = "The Open Source Way 中文版"

[build]
build-dir = "book"

[output.html]
default-theme = "light"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/theopensourcewaycn/guidebook"
edit-url-template = "https://github.com/theopensourcewaycn/guidebook/edit/main-cn/{path}"

[output.html.fold]
enable = true
level = 1

[output.html.search]
enable = true
limit-results = 30

# Pandoc 输出配置（用于生成 PDF）
[output.pandoc]
optional = true

[output.pandoc.profile.pdf]
output-file = "guidebook.md"
standalone = true
